# Artificial Neural Network

In [ ]:
# Importing the libraries

In [1]:

















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.10.0'

# Part 1 : Data Preprocessing

In [2]:
# Importing the dataset
df = pd.read_csv(r"C:\Users\hp\Downloads\24th\ANN_ cpu\Churn_Modelling.csv")
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values
print(X)
print(y)
df

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\.conda\envs\tensorflow_env\lib\site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\hp\.conda\envs\tensorflow_env\lib\site-packages (from scikit-learn) (1.25.0)
Requirement already satisfied: scipy>=1.5.0 in c:\users\hp\.conda\envs\tensorflow_env\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\hp\.conda\envs\tensorflow_env\lib\site-packages (from scikit-learn) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\hp\.conda\envs\tensorflow_env\lib\site-packages (from scikit-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]

In [5]:
# One Hot Encoding the "Geography" colum

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [8]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

# Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Part 2 - Building the ANN

In [ ]:
# Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

In [ ]:
# Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
# Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
# Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Training the ANN

In [ ]:
# Compiling the ANN

In [12]:
ann.compile(optimizer='adam',loss ='binary_crossentropy',metrics=['accuracy'])

# Training the ANN on the Training set

In [14]:
ann.fit(X_train, y_train,batch_size=32,epochs=10)

Epoch 1/10
250/250 [==============================] - 1s 709us/step - loss: 0.7618 - accuracy: 0.5645
Epoch 2/10
250/250 [==============================] - 0s 696us/step - loss: 0.6156 - accuracy: 0.6531
Epoch 3/10
250/250 [==============================] - 0s 686us/step - loss: 0.5376 - accuracy: 0.7509
Epoch 4/10
250/250 [==============================] - 0s 693us/step - loss: 0.4967 - accuracy: 0.7947
Epoch 5/10
250/250 [==============================] - 0s 772us/step - loss: 0.4730 - accuracy: 0.8036
Epoch 6/10
250/250 [==============================] - 0s 793us/step - loss: 0.4579 - accuracy: 0.8050
Epoch 7/10
250/250 [==============================] - 0s 796us/step - loss: 0.4480 - accuracy: 0.8066
Epoch 8/10
250/250 [==============================] - 0s 710us/step - loss: 0.4415 - accuracy: 0.8066
Epoch 9/10
250/250 [==============================] - 0s 713us/step - loss: 0.4371 - accuracy: 0.8067
Epoch 10/10
250/250 [==============================] - 0s 712us/step - loss: 0.4344 - accuracy: 0.8075

# Part 4 - Making the predictions and evaluating the model

In [ ]:
#Predicting the Test set results

In [16]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 588us/step

In [20]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))  # predicted and actual value conactenation

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]

# Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1526   69]
 [ 308   97]]